# Local LLM
spring.ai.openai.api-key=ignored

#docker
spring.ai.openai.base-url=http://localhost:12434/engines
spring.ai.openai.chat.options.model=ai/gemma4:12B

#ollama
#spring.ai.openai.base-url=http://localhost:11434
#spring.ai.openai.chat.options.model=gemma4:12B

#logging.level.org.springframework.ai=DEBUG

# Sync mode for easier local debugging (LLM calls on caller thread)
code2req.execution.execution-mode=sync

